# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbc3bfda53d85e99cd3669570be7f8ea14558c8bdbda3da2c7ea74e9e4f7951e40906020ff9b92f6f53e1734ae27422bdecd00d98d2e2b94163a5eb049c6c0ea

test:
  secret_key_base: 9644515fa170ce2eb367fe96a4f6a67db522ead54fdc8e961fca18360ce04707c0ff51d556076f31c82ae07f3ea634e8bd86edbf5f6e314e971774ff79d98abd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
